# Generated by Django 4.2.4 on 2023-08-15 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('tizer', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y.%m.%d/gallary/')),
                ('title', models.CharField(max_length=256)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
            ],
            options={
                'verbose_name': 'Galareya surati',
                'verbose_name_plural': 'Galareya suratlari',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeded_url', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Xarita',
                'verbose_name_plural': 'Xaritalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y.%m.%d/news/')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('big_text', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y.%m.%d/partner/')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y.%m.%d/plans/')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Kelgusi tadbir',
                'verbose_name_plural': 'Kelgusi tadbirlar',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y.%m.%d/team/')),
                ('name', models.CharField(max_length=256)),
                ('profession', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Jamoa azosi',
                'verbose_name_plural': 'Jasmoa azolari',
            },
        ),
    ]
