# Generated by Django 4.2.4 on 2023-09-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='title',
        ),
    ]
